import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import MenuAdmin from "@/components/admin/MenuAdmin";
import HeaderAdmin from "@/components/admin/HeaderAdmin";

export const metadata: Metadata = {
  title: "Client Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange>
      <div className="flex min-h-screen w-full flex-col bg-muted/40">
        <MenuAdmin />
        <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
          <HeaderAdmin />
          {children}
        </div>
      </div>
    </ThemeProvider>
  );
}
